# Generated by Django 5.2.1 on 2026-06-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captain',
            name='team',
        ),
        migrations.AddField(
            model_name='captain',
            name='level',
            field=models.CharField(choices=[('BV', 'Boys Varsity'), ('GV', 'Girls Varsity'), ('JVB', 'Junior Varsity Boys'), ('JVG', 'Junior Varsity Girls'), ('U14B', 'Boys U14s A'), ('U14G', 'Girls U14s A'), ('14B', 'U14s B'), ('y7', 'Year 7')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='captain',
            name='sport',
            field=models.CharField(choices=[('VB', 'Volleyball'), ('FB', 'Football'), ('BB', 'Basketball'), ('TE', 'Tennis'), ('BD', 'Badminton'), ('TR', 'Track & Field'), ('SW', 'Swimming')], default=2),
            preserve_default=False,
        ),
    ]
