# Generated by Django 5.2.1 on 2026-07-09 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0047_alter_player_image_alter_team_level_and_more'),
        ('users', '0002_remove_captain_team_captain_level_captain_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sports.level'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sports.sport'),
        ),
    ]
