# Generated by Django 5.2.1 on 2025-09-02 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Boys Volleyball, Girls Soccer', max_length=100)),
                ('sport', models.CharField(choices=[('VB', 'Mens Volleyball'), ('FB', 'Boys Football'), ('BB', 'Basketball'), ('GVB', 'Girls Volleyball'), ('GFB', 'Girls Football'), ('GBB', 'Girls Basketball'), ('TE', 'Tennis'), ('BD', 'Badminton'), ('TR', 'Track & Field'), ('SW', 'Swimming')], max_length=5)),
                ('level', models.CharField(choices=[('V', 'Varsity'), ('JV', 'Junior Varsity'), ('U14', 'U14s A'), ('14A', 'U14s A'), ('14B', 'U14s A'), ('y7', 'Year 7')], max_length=5)),
                ('coach', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(blank=True, help_text='e.g., Fall 2024, Winter 2024-25', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief team description or motto')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teams/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('honors', models.CharField(help_text='Honors', max_length=100)),
            ],
            options={
                'ordering': ['sport', 'level', 'name'],
                'unique_together': {('name', 'sport', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('grade', models.CharField(blank=True, help_text='e.g., 9th, 10th, 11th, 12th', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/photos/')),
                ('is_captain', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sports.team')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
