# Generated by Django 5.2.1 on 2025-09-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.CharField(choices=[('BV', 'Boys Varsity'), ('GV', 'Girls Varsity'), ('JV', 'Junior Varsity'), ('U14B', 'Boys U14s A'), ('U14G', 'Girls U14s'), ('14B', 'U14s A'), ('y7', 'Year 7')], max_length=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('VB', 'Volleyball'), ('FB', 'Football'), ('BB', 'Basketball'), ('VB', 'Volleyball'), ('FB', 'Football'), ('BB', 'Basketball'), ('TE', 'Tennis'), ('BD', 'Badminton'), ('TR', 'Track & Field'), ('SW', 'Swimming')], max_length=5),
        ),
    ]
