# Generated by Django 5.2.1 on 2025-09-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_alter_team_level_alter_team_sport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='grade',
            new_name='year',
        ),
    ]
