# Generated by Django 5.2.1 on 2025-09-09 00:14

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_rename_grade_player_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='opposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('opp_logo', models.ImageField(blank=True, null=True, upload_to='teams/opposition/photos/')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='shirt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcb_score', models.CharField(max_length=5)),
                ('opp_score', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('dcb_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcb_team', to='sports.team')),
                ('opposition', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='opposition_team', to='sports.opposition')),
            ],
        ),
    ]
