# Generated by Django 5.2.1 on 2025-09-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_opposition_player_shirt_number_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='teams/events/')),
            ],
        ),
    ]
