# Generated by Django 5.2.1 on 2025-09-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='event',
        ),
        migrations.RenameModel(
            old_name='games',
            new_name='game',
        ),
    ]
