# Generated by Django 5.2.1 on 2025-09-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_rename_events_event_rename_games_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dcb_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='opp_score',
            field=models.IntegerField(),
        ),
    ]
