# Generated by Django 5.2.1 on 2025-09-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.IntegerField(blank=True, default=2025, help_text='e.g., 9th, 10th, 11th, 12th'),
        ),
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.CharField(choices=[('Season 1', '1'), ('Season 2', '2'), ('Season 3', '3'), ('4', 'Season 4')], max_length=10),
        ),
    ]
