# Generated by Django 5.2.1 on 2025-10-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_team_year_alter_team_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='quote',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('VB', 'Volleyball'), ('FB', 'Football'), ('BB', 'Basketball'), ('TE', 'Tennis'), ('BD', 'Badminton'), ('TR', 'Track & Field'), ('SW', 'Swimming')], max_length=5),
        ),
    ]
