# Generated by Django 5.2.1 on 2025-10-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_player_quote_alter_team_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='players/photos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.CharField(choices=[('1', 'Season 1'), ('Season 2', '2'), ('Season 3', '3'), ('Season 4', '4')], max_length=10),
        ),
    ]
