# Generated by Django 5.2.1 on 2025-10-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0012_team_instagram_alter_player_photo_alter_team_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.CharField(choices=[('1', 'Season 1'), ('2', 'Season 2'), ('Season 3', '3'), ('Season 4', '4')], max_length=10),
        ),
    ]
