# Generated by Django 5.2.1 on 2025-10-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0013_alter_team_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('teams', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='legends/')),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.CharField(choices=[('Season 1', '1'), ('Season 2', '2'), ('Season 3', '3'), ('4', 'Season 4')], max_length=10),
        ),
    ]
