# Generated by Django 5.2.1 on 2025-10-26 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0014_legend_alter_team_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
        migrations.AlterField(
            model_name='legend',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='legend',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='legends/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.CharField(choices=[('1', 'Season 1'), ('2', 'Season 2'), ('3', 'Season 3'), ('4', 'Season 4')], max_length=10),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student_coach', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='legends/')),
                ('year', models.CharField(blank=True, help_text='e.g., 9th, 10th, 11th, 12th', max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='sports.team')),
            ],
        ),
    ]
