# Generated by Django 5.2.1 on 2025-10-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0015_remove_team_coach_alter_legend_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='image',
            new_name='photo',
        ),
    ]
