# Generated by Django 5.2.1 on 2026-05-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0016_rename_image_coach_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
