# Generated by Django 5.2.1 on 2026-06-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0017_player_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='honors',
        ),
        migrations.AlterField(
            model_name='player',
            name='year',
            field=models.IntegerField(blank=True, choices=[(7, 'Year 7'), (8, 'Year 8'), (9, 'Year 9'), (10, 'Year 10'), (11, 'Year 11'), (12, 'Year 12'), (13, 'Year 13')], max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='year',
            field=models.IntegerField(blank=True, default=2025, help_text='e.g., 2025... 2026... 2027'),
        ),
    ]
