# Generated by Django 5.2.1 on 2026-06-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0018_remove_team_honors_alter_player_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='e.g., Boys Volleyball, Girls football', max_length=100),
        ),
    ]
