# Generated by Django 5.2.1 on 2026-06-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0019_legend_is_correct_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='opposition',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='opposition',
        ),
    ]
