# Generated by Django 5.2.1 on 2026-06-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0020_alter_game_opposition_delete_opposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dcb_score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='opp_score',
            field=models.PositiveIntegerField(),
        ),
    ]
