# Generated by Django 5.2.1 on 2026-06-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0021_alter_game_dcb_score_alter_game_opp_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='year',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='year',
            field=models.IntegerField(blank=True, choices=[(7, 'Year 7'), (8, 'Year 8'), (9, 'Year 9'), (10, 'Year 10'), (11, 'Year 11'), (12, 'Year 12'), (13, 'Year 13')]),
        ),
    ]
