# Generated by Django 5.2.1 on 2026-06-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0022_legend_year_alter_player_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legend',
            old_name='year',
            new_name='class_of',
        ),
    ]
