# Generated by Django 5.2.1 on 2026-06-15 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0023_rename_year_legend_class_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend',
            name='class_of',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2025)]),
        ),
    ]
