# Generated by Django 5.2.1 on 2026-06-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0024_alter_legend_class_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Only published teams are visible to the public'),
        ),
        migrations.AddField(
            model_name='team',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.CharField(choices=[('BV', 'Boys Varsity'), ('GV', 'Girls Varsity'), ('JVB', 'Junior Varsity Boys'), ('JVG', 'Junior Varsity Girls'), ('U14B', 'Boys U14s A'), ('U14G', 'Girls U14s A'), ('14B', 'U14s B'), ('y7', 'Year 7')], max_length=5),
        ),
    ]
