# Generated by Django 5.2.1 on 2026-06-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0025_team_is_published_team_priority_alter_team_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_academic_year', models.IntegerField(help_text='Use the school-year start year, e.g. 2025 for 2025-2026')),
            ],
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['priority']},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='team',
            name='priority',
            field=models.IntegerField(default=1, help_text='1=Varsity, 2=JV, 3=Lower teams (lower number = higher on page)'),
        ),
    ]
