# Generated by Django 5.2.1 on 2026-06-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0026_sitesettings_alter_team_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='year',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
