# Generated by Django 5.2.1 on 2026-06-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0027_remove_coach_year_remove_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.CharField(choices=[('BV', 'Boys Varsity'), ('GV', 'Girls Varsity'), ('JVB', 'Junior Varsity Boys'), ('JVG', 'Junior Varsity Girls'), ('U14B', 'Boys U14s A'), ('U14G', 'Girls U14s A'), ('14B', 'U14s B'), ('y7', 'Year 7')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('VB', 'Volleyball'), ('FB', 'Football'), ('BB', 'Basketball'), ('TE', 'Tennis'), ('BD', 'Badminton'), ('TR', 'Track & Field'), ('SW', 'Swimming')]),
        ),
    ]
