# Generated by Django 5.2.1 on 2026-06-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0028_alter_team_level_alter_team_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='coaches/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='dcb_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='opp_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
