# Generated by Django 5.2.1 on 2026-06-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0029_alter_coach_photo_alter_game_dcb_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='photo',
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='players/'),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
    ]
