# Generated by Django 5.2.1 on 2026-07-04 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0030_rename_photo_coach_image_remove_player_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Boys Varsity, U12 Boys', max_length=50, unique=True)),
                ('code', models.CharField(help_text='e.g., BV, U12B', max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Volleyball, Rugby', max_length=50, unique=True)),
                ('code', models.CharField(help_text='e.g., VB, FB ', max_length=5, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='sports.level'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='sports.sport'),
        ),
    ]
