# Generated by Django 5.2.1 on 2026-07-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0032_remove_team_level_remove_team_sport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
