# Generated by Django 5.2.1 on 2026-07-04 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0034_team_level_team_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Boys Varsity, U12 Boys', max_length=50, unique=True)),
                ('code', models.CharField(help_text='e.g., BV, U12B', max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Volleyball, Rugby', max_length=50, unique=True)),
                ('code', models.CharField(help_text='e.g., VB, FB ', max_length=5, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sports.level'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sports.sport'),
        ),
    ]
