# Generated by Django 5.2.1 on 2026-07-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0035_level_sport_alter_team_level_alter_team_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='level',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sport',
        ),
    ]
