# Generated by Django 5.2.1 on 2026-07-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0036_remove_team_level_remove_team_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.ForeignKey(db_constraint=False, default=2, on_delete=django.db.models.deletion.PROTECT, to='sports.level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.PROTECT, to='sports.sport'),
            preserve_default=False,
        ),
    ]
