# Generated by Django 5.2.1 on 2026-07-08 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0041_auto_20260708_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sports.level'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sports.sport'),
        ),
    ]
