# Generated by Django 5.2.1 on 2026-07-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0042_alter_team_level_alter_team_sport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='level',
            new_name='new_level',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='sport',
            new_name='new_sport',
        ),
    ]
