# Generated by Django 5.2.1 on 2026-07-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0043_rename_level_team_new_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='new_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='new_sport',
            new_name='sport',
        ),
    ]
