# Generated by Django 5.2.1 on 2026-07-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0044_rename_new_level_team_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
