# Generated by Django 5.2.1 on 2026-07-09 10:08

import django.db.models.deletion
import sports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0046_alter_event_date_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sports.level'),
        ),
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.CharField(choices=[('1', 'Season 1'), ('2', 'Season 2'), ('3', 'Season 3'), ('4', 'Season 4'), ('all', 'All season')], max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sports.sport'),
        ),
        migrations.AlterField(
            model_name='team',
            name='year',
            field=models.IntegerField(blank=True, default=sports.models.SiteSettings.get_current_year, help_text='e.g., 2025... 2026... 2027'),
        ),
    ]
