# Generated by Django 5.2.1 on 2026-07-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0047_alter_player_image_alter_team_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
