# Generated by Django 5.2.1 on 2026-07-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0048_alter_game_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['is_student_coach']},
        ),
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.CharField(choices=[('1', 'Season 1'), ('2', 'Season 2'), ('3', 'Season 3'), ('4', 'Season 4'), ('5', 'All season')], max_length=10),
        ),
    ]
