# Generated by Django 5.2.1 on 2026-07-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0049_alter_coach_options_alter_team_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='year',
            field=models.IntegerField(choices=[(7, 'Year 7'), (8, 'Year 8'), (9, 'Year 9'), (10, 'Year 10'), (11, 'Year 11'), (12, 'Year 12'), (13, 'Year 13')]),
        ),
    ]
