# Generated by Django 5.2.1 on 2026-07-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0050_alter_player_position_alter_player_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
